services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__ROOT_URL=https://forgejo.home.disconnesso.com
      - FORGEJO__server__SSH_DOMAIN=192.168.100.100
      - FORGEJO__server__SSH_PORT=222
      - FORGEJO__service__DISABLE_REGISTRATION=true
    restart: unless-stopped
    volumes:
      - forgejo_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3100:3000"
      - "222:22"
    mem_limit: 512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/version"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  forgejo_data:
