- search:
    provider: google
    target: _blank
- resources:
    cpu: true
    memory: true
    disk: /
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
- openmeteo:
    label: Rome
    latitude: 41.89
    longitude: 12.49
    timezone: Europe/Rome
    units: metric
